name: IntegrationTest
# Need GitHub secret: DOCKER_HUB_USER, DOCKER_HUB_SECRETS, GHCR_TOKEN

on:
  push:
    branches:
      - master
      - tekton-support
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'
      - 'tekton-support'

jobs:
  IntegrationTest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.13
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.13
        id: go
      - name: Prepare integration test environment
        run: |
          curl -L https://github.com/linuxsuren/http-downloader/releases/latest/download/hd-linux-amd64.tar.gz | tar xzv
          mv hd /usr/local/bin
          sudo hd fetch
          sudo hd install kubectl
          curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
          k3d cluster create
      - name: Integration test
        run: |
          make tekton-support-integration-test
